"use client";

import { useEffect, useState, useCallback } from "react";
import { FullScreenCalendar } from "@/components/ui/fullscreen-calendar";

interface CalendarEvent {
  id: string;
  title: string;
  start: string;
  end: string;
  type: string;
  meta?: any;
}

interface CalendarTabProps {
  showMock?: boolean;
  autoOpenEventId?: string | null;
}

export default function CalendarTab({ showMock, autoOpenEventId }: CalendarTabProps) {
  const [events, setEvents] = useState<CalendarEvent[]>([]);

  const refresh = useCallback(async () => {
    try {
      const res = await fetch("/api/calendar/events");
      let apiData = res.ok ? await res.json().catch(() => ({ events: [] })) : { events: [] };
      let combinedEvents = apiData.events ?? [];

      if (showMock) {
        const mockEvents: CalendarEvent[] = [
          {
            id: "mock-note-1",
            title: "Example Note: Linear Algebra Lecture",
            start: new Date().toISOString(),
            end: new Date().toISOString(),
            type: "note",
            meta: {
              courseCode: "MATH1001",
              courseName: "Linear Algebra",
              description: "An example of a lecture note generated by AI. It includes key concepts like vector spaces and linear transformations."
            }
          },
          {
            id: "mock-assignment-1",
            title: "Example Assignment: Final Project",
            start: new Date(Date.now() + 86400000 * 3).toISOString(), // 3 days from now
            end: new Date(Date.now() + 86400000 * 3).toISOString(),
            type: "assignment",
            meta: {
              courseCode: "COMP1234",
              courseName: "Design Project",
              weight: 0.25,
              maxGrade: 100,
              description: "This is what an assignment looks like. It shows the weighting, max grade, and due date."
            }
          }
        ];
        combinedEvents = [...combinedEvents, ...mockEvents];
      }
      setEvents(combinedEvents);
    } catch (err) {
      console.error("Failed to refresh calendar events", err);
    }
  }, [showMock]);

  useEffect(() => {
    void refresh();
  }, [refresh]);

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white">Calendar</h2>
          <p className="text-xs text-gray-500 dark:text-gray-400">
            Shows uni assignment due dates, note creation dates, and Canvas events.
          </p>
        </div>
      </div>
      <div className="rounded-xl border border-gray-200 dark:border-[#1F1F23] bg-white dark:bg-[#0F0F12] p-4 text-gray-900 dark:text-white">
        <FullScreenCalendar
          events={events}
          onRefresh={refresh}
          autoOpenEventId={autoOpenEventId}
        />
      </div>
    </div>
  );
}
